### PR TITLE
jQuery.deparam: coerce standalone keys to null values

### PR DESCRIPTION
**Pull request by jayaddison**
This pull request adds support for a `standaloneKeys` parameter to the `jQuery.deparam` function, allowing clients to decode standalone query-string keys (e.g. the key `b` in the string `?a=1&b&c=3`) as `null`.

Standalone keys are deserialized to nulls only when the `coerce` parameter is also enabled.  Backwards-compatibility is maintained with prior versions of the `jquery-bbq` library, and test coverage to illustrate this is provided.

This proposed change corresponds to https://github.com/jquery/jquery/pull/4708 in which the ability to serialize JavaScript objects containing `null` values to query strings is proposed.

### CODE REVIEW

**Comment by jayaddison** [comment]
Todo:

- [x] Minify `jquery.ba-bbq.js` -> `jquery.ba-bbq.min.js`

**Comment by jayaddison** [comment]
>     * [x]  Minify `jquery.ba-bbq.js` -> `jquery.ba-bbq.min.js`

Minified by using [yui-compressor](https://github.com/yui/yuicompressor) v2.4.8, and confirmed that unit tests continue to pass against the minified file ([ref](https://github.com/cowboy/jquery-bbq/blob/950bfc1780af97e0753172c99184863d29dbc3e8/unit/index.html#L10)).

**Comment by jayaddison** [comment]
@cowboy This might be a bit like ancient archeology, but I wondered if you'd entertain the idea of releasing an updated version of `jquery-bbq`?  (currently just north of a decade since the previous release :))

Change #48 looks innocuous, and now that I've read #62 I'd be keen to deploy a version with that resolved.  This pull request is less important.  If maintenance is a pain then perhaps a fork is an alternative; figured I'd ask first though.

**Comment by cowboy** [comment]
@jayaddison unfortunately, I don't have any of the tools set up to actually generate the requisite files for this project (and this was way before I had anything like Grunt, in fact, it's the reason I created Grunt in the first place). Are you interested in doing the work to make this happen? If so, I can give you access to manage the repo and merge in those changes.

**Comment by jayaddison** [comment]
@cowboy It's been a little while since looking at this, but from what I remember, I was able to rebuild and minify distributable JS code although it was a slightly manual process at the time (ref previous comment).

I'd be glad to do a bit of maintenance here, and perhaps modernize the build process after understanding it a bit more fully.

**Comment by cowboy** [comment]
@jayaddison invite sent!

**Comment by jayaddison** [comment]
@cowboy A heads-up that although I made a [tiny amount of progress](https://github.com/cowboy/jquery-bbq/commit/ed131cc1c875612ad8106f7fe201c8b746590852) on adding an updated build process, this hasn't been something I've been able to progress a lot yet.

It'd be nice to merge some pending security-related improvements, but in the absence of progress on those or other features, it might be worth dropping my access privileges on the repo.  Maybe an idea worth revisiting in another week or two.

**Comment by jayaddison** [comment]
@cowboy Just a heads-up that I'm going to bow out of that effort to update the build process here, and drop my privileges on the repository; other time commitments are taking priority.  It seemed worth a try, but I didn't make much progress unfortunately!

**Comment by jayaddison** [comment]
I think this issue can probably be closed - perhaps at some point I'd like to revive a debate about standalone keys in query-strings, but until then this can be closed (with commits still retrievable via the github pr ref).

**Pull request closed without merging**
