### PR TITLE
Keep interface of browser.msie, after jquery 1.9 removed from core.

### PR DESCRIPTION
**Pull request by dadario**
jQuery 1.9 removes $.browser. Using the same solution that jquery-simple-modal used to keep compatibility.

### CODE REVIEW

**Comment by bjorn-ali-goransson** [comment]
+1...

**Comment by joscha** [comment]
@dadario Good work! Would be awesome if you could also update the minified one :)

**Comment by trickortweak** [comment]
Excellent work, thanks for including the minified js as well.

**Comment by bartosz-zawada** [comment]
Thank you.

**Comment by atdt** [comment]
Please?

**Pull request closed without merging**
